CREATE DATABASE IF NOT EXISTS bd_pacientes;
CREATE DATABASE IF NOT EXISTS bd_facturaciones;
CREATE DATABASE IF NOT EXISTS bd_recetas;
CREATE DATABASE IF NOT EXISTS bd_notificaciones;
CREATE DATABASE IF NOT EXISTS bd_medicos;
CREATE DATABASE IF NOT EXISTS bd_historial_clinico;
CREATE DATABASE IF NOT EXISTS bd_examenes;
CREATE DATABASE IF NOT EXISTS bd_citas;