CREATE TABLE medicos(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    especialidad VARCHAR(100) NOT NULL,
    telefono VARCHAR(15)  NOT NULL,
    email VARCHAR(100) NOT NULL
);
